### ISSUE TITLE
ValueError on delete() 

### ISSUE THREAD

**Issue by jrheling** [andreffs18/sheetsu-python#2]
Using the delete() method, e.g. `rows_deleted = c.delete(sheet="Sheet1", column="item", value=del_item)` results in:

> Traceback (most recent call last):
  File "./sheetsu_delete.py", line 20, in <module>
  rows_deleted = c.delete(sheet="Sheet1", column="item", value=del_item)
  File "/usr/local/lib/python2.7/site-packages/sheetsu/client.py", line 35, in delete
  return DeleteResource(self)(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/sheetsu/core/delete.py", line 20, in __call__
  return super(DeleteResource, self).__call__(**payload)
  File "/usr/local/lib/python2.7/site-packages/sheetsu/core/core.py", line 73, in __call__
  return json.loads(r.content)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
  return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
  obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
  raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

I'm pretty sure this is because the underlying sheetsu API doesn't return anything from the "Clear" type of delete, per https://docs.sheetsu.com/?shell#delete. It *does* return from the "Destroy" type of delete, but that doesn't seem to be supported by sheetsu-python.

**Comment by andreffs18** [comment]
Closing this issue now since the PR was already merged
